## Tests Configurations

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/df_pkill.csv', delimiter = ',',header=0)
df

,alt_sht,vel_sht,pit_sht,alt_tgt,vel_tgt,hdg_tgt,rgt_tgt,dist,delay,turn_dg,pkill
0,1900.094833,516.257515,-9.115002,9411.674491,389.059516,-179.508724,28.173016,22.107204,24.962478,5.107690,0.087
1,1668.030968,384.114554,-9.291737,6424.170046,538.332386,150.564222,21.635788,42.957053,27.889110,140.635249,0.016
2,1430.046650,552.946387,-16.802029,11292.969864,536.495037,-71.258760,47.099787,17.904767,28.814680,13.967480,0.070
3,1819.812543,524.681447,2.326836,3983.583185,354.232941,-147.655375,-25.450868,38.858097,25.736859,47.110727,0.020
4,1348.600786,367.370819,13.801087,8269.417066,533.015720,85.274320,-47.226769,27.176054,17.912385,137.619306,0.024
...,...,...,...,...,...,...,...,...,...,...,...
2855050,44376.436551,544.473934,-4.773440,16868.508237,620.848721,83.157352,32.501000,32.909110,21.978916,71.510008,0.031
2855051,44396.062176,555.458863,-12.651975,44331.857296,626.047542,28.146378,-26.005787,42.962424,27.934929,145.538436,0.024
2855052,44373.716110,609.965112,-24.517640,16754.178594,580.015564,168.638639,-16.550910,43.350364,15.081863,79.534893,0.043
2855053,44432.347726,617.846742,11.024131,24860.378262,658.322238,-145.516952,14.465779,40.760772,26.462078,84.072836,0.111
2855054,44678.656616,558.896145,16.252619,19450.140698,644.534022,-63.727657,-52.439259,35.887900,16.159216,41.072911,0.031

In [3]:
df2=df[(df['pkill']>70)]
df2

,alt_sht,vel_sht,pit_sht,alt_tgt,vel_tgt,hdg_tgt,rgt_tgt,dist,delay,turn_dg,pkill
6,1848.302744,447.678029,-23.331690,18069.782622,473.468211,144.390464,-40.104475,6.033080,27.654833,157.501845,76.332
72,1335.727183,307.094963,17.734832,16539.095071,375.834833,164.293180,-11.219515,15.424677,20.777362,24.424025,92.072
85,1817.205657,419.873740,-22.299365,12319.860614,305.813375,-159.095097,15.475607,8.092716,18.104150,32.045722,84.953
104,1560.340725,348.216082,-29.982093,4630.054192,372.639455,157.014831,3.575613,7.911295,28.163559,58.768327,93.350
127,1321.432638,589.276473,26.902712,7024.394359,569.794135,70.237848,-42.544100,5.957655,25.038953,36.594666,80.128
...,...,...,...,...,...,...,...,...,...,...,...
2855022,44968.474472,585.878659,4.005639,41221.800244,524.343253,65.085192,-9.524541,18.347268,22.388918,59.719349,79.098
2855029,44907.665126,597.358138,18.391505,38649.360324,486.479485,-75.639062,-21.422301,25.742795,20.544518,146.562088,91.324
2855032,44735.438633,526.609604,26.377218,33853.117946,487.872603,-178.042105,6.025939,37.920806,21.999767,42.787916,79.052
2855035,44056.104133,532.970782,5.645153,20110.685665,635.927159,169.828272,7.987811,13.870489,18.696892,89.133429,89.947
2855038,44577.776567,603.256523,-1.073668,28321.632247,617.751180,-162.820120,-19.043463,17.106221,26.526568,130.925022,72.749

In [4]:
df3=df2[(df2['hdg_tgt']<30) & (df2['hdg_tgt']>28)]
df3

,alt_sht,vel_sht,pit_sht,alt_tgt,vel_tgt,hdg_tgt,rgt_tgt,dist,delay,turn_dg,pkill
13799,1681.673949,474.135397,19.290775,1244.774367,300.434583,28.039865,19.808373,6.767348,15.385260,136.701255,72.822
190772,4983.984236,509.002987,4.072513,16217.499004,305.306064,28.831262,-37.997986,7.550898,24.363240,1.003813,71.172
235836,6491.341924,397.257941,-17.477739,5789.241632,420.684455,29.064113,-56.799207,5.080919,28.053917,17.457267,76.087
240528,6092.648059,386.443759,19.423970,12655.181202,307.875823,28.479086,2.144247,8.689527,28.296225,178.181920,82.435
272078,5098.161096,579.988707,-15.996268,16088.907024,342.385921,28.206570,16.026876,5.035129,20.680256,30.479056,70.614
...,...,...,...,...,...,...,...,...,...,...,...
2850446,44071.244110,630.606937,23.044482,25853.544034,644.599776,29.782046,-54.802411,10.129395,17.024925,175.436748,84.210
2850985,44040.734758,573.223920,-20.013460,29087.991738,465.553128,28.056049,20.652817,10.969643,23.444189,109.218670,83.679
2854062,44935.805533,565.525347,13.127499,44863.043280,510.557565,28.919015,-28.734692,11.156634,29.598255,13.272138,96.351
2854115,44589.713601,537.814652,0.898598,34117.116646,515.349952,28.199118,51.764827,13.735956,27.589353,71.596768,70.667
2854784,44771.144509,623.069988,-0.526995,35003.888217,503.711751,28.374846,46.223329,13.182027,23.276816,75.164300,73.252

In [5]:
df4=df3[(df3['rgt_tgt']<-29) & (df3['rgt_tgt']>-30)]
df4

,alt_sht,vel_sht,pit_sht,alt_tgt,vel_tgt,hdg_tgt,rgt_tgt,dist,delay,turn_dg,pkill
1677357,23329.167356,499.911408,12.436550,26670.299962,588.259973,28.103154,-29.780902,6.641562,19.616950,137.478711,82.046
1867088,25488.349699,558.153214,-28.852118,18542.923469,341.602116,29.520046,-29.483545,6.943391,20.131044,27.430006,85.230
1871224,25618.727094,611.001456,-17.108637,33235.523738,552.981710,28.979704,-29.255088,5.079683,24.134804,106.766586,97.202
1960668,26182.599894,621.317393,-9.842592,44807.302972,340.904316,28.553766,-29.892435,5.849045,16.422461,1.033763,89.827
2007790,28421.913996,448.053835,18.838412,30453.552731,347.875569,28.407107,-29.463899,6.934518,18.859517,94.674105,76.698
2148718,29812.184498,508.883469,-11.611043,18172.329636,482.456777,28.648813,-29.539268,6.197400,17.463424,96.830880,91.456
2278289,31032.773737,491.716682,-5.907363,42244.396436,379.578933,29.960704,-29.796471,12.210232,24.413892,91.893705,82.034
2738517,40625.362436,534.937582,3.088404,15573.345350,578.448970,28.922189,-29.694796,7.935926,27.646228,158.640731,77.725
2804557,43469.087126,628.485803,-20.318678,42703.735968,481.164827,29.370185,-29.497334,11.243329,27.318323,117.511800,79.832

In [6]:
df[df['dist']>20]

,alt_sht,vel_sht,pit_sht,alt_tgt,vel_tgt,hdg_tgt,rgt_tgt,dist,delay,turn_dg,pkill
0,1900.094833,516.257515,-9.115002,9411.674491,389.059516,-179.508724,28.173016,22.107204,24.962478,5.107690,0.087
1,1668.030968,384.114554,-9.291737,6424.170046,538.332386,150.564222,21.635788,42.957053,27.889110,140.635249,0.016
3,1819.812543,524.681447,2.326836,3983.583185,354.232941,-147.655375,-25.450868,38.858097,25.736859,47.110727,0.020
4,1348.600786,367.370819,13.801087,8269.417066,533.015720,85.274320,-47.226769,27.176054,17.912385,137.619306,0.024
5,1765.370864,328.856531,-9.682175,11630.551419,405.232301,-146.154950,43.638239,35.745262,19.770389,89.597699,0.026
...,...,...,...,...,...,...,...,...,...,...,...
2855050,44376.436551,544.473934,-4.773440,16868.508237,620.848721,83.157352,32.501000,32.909110,21.978916,71.510008,0.031
2855051,44396.062176,555.458863,-12.651975,44331.857296,626.047542,28.146378,-26.005787,42.962424,27.934929,145.538436,0.024
2855052,44373.716110,609.965112,-24.517640,16754.178594,580.015564,168.638639,-16.550910,43.350364,15.081863,79.534893,0.043
2855053,44432.347726,617.846742,11.024131,24860.378262,658.322238,-145.516952,14.465779,40.760772,26.462078,84.072836,0.111
2855054,44678.656616,558.896145,16.252619,19450.140698,644.534022,-63.727657,-52.439259,35.887900,16.159216,41.072911,0.031